name: ci
 
on:
 push:
   branches: '*'
 
jobs:
 main:
   runs-on: ubuntu-20.04
   steps:
     - name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         platforms: linux/amd64,linux/arm/v7
         tags: timja/core-pr-tester:latest